FROM postgres:latest
ENV POSTGRES_USER ${POSTGRES_DATABASE_USER}
ENV POSTGRES_PASSWORD ${POSTGRES_DATABASE_PASSWORD}
ENV POSTGRES_DB ${POSTGRES_DATABASE_NAME}

COPY ./prisma/migrations/**/*.sql /docker-entrypoint-initdb.d/